### ISSUE TITLE
Setting properties using \Ease\Functions::cfg()

### ISSUE THREAD

**Issue by petaak** [VitexSoftware/php-ease-core#2]
After updating to the 1.8 version, my integration of https://github.com/Spoje-NET/php-flexibee does not work. It's because the \Ease\Molecule::setupProperty method sets the \FlexiPeeHP\FlexiBeeRO::$defaultUrlParams property to null, but is't expected to be an array.

Shouldn't on this line https://github.com/VitexSoftware/php-ease-core/blob/main/src/Ease/Molecule.php#L67 be:
`            
if (empty(\Ease\Functions::cfg($constant)) === false) {
` 
instead of:
`
if (empty(\Ease\Functions::cfg($constant) === false)) {
` ?

**Comment by Vitexus** [comment]
Fixed. 
![obrazek](https://user-images.githubusercontent.com/2621130/97089002-094c3880-1635-11eb-9a59-2ea11955f3c9.png)
Please wait for releases

**Comment by Vitexus** [comment]
Please update to https://github.com/VitexSoftware/php-ease-core/releases/tag/1.8.1

**Comment by petaak** [comment]
Thanks.
