### ISSUE TITLE
Duplicate filename error

### ISSUE THREAD

**Issue by janharsa** [VitexSoftware/php-ease-core#3]
Composer have a problem with duplicate files (one with capital and another without)

![image](https://user-images.githubusercontent.com/8598725/100856364-a0ee4380-348b-11eb-8584-817af29bc1b7.png)

[RuntimeException]

The archive may contain identical file names with different capitalization (which fails on case insensitive filesystems): ZipArchive::extractTo(/srv/vendor/composer/1dd9bfc6/VitexSoftware-php-ease-core-3a20e1a/doc/packages/default.html): failed to open stream: File exists

[ErrorException]

ZipArchive::extractTo(/srv/vendor/composer/1dd9bfc6/VitexSoftware-php-ease-core-3a20e1a/doc/packages/default.html): failed to open stream: File exists

**Comment by Vitexus** [comment]
Thank you for the patch. 
There is some tool for composer that is able remove all non php files to make vendor small. 
I want recommend it. But i cannot find it :(

**Comment by Vitexus** [comment]
There was unused switch --defaultpackagename 
Is used now :)
